### ISSUE TITLE
raise cls.CannotDetector (AttributeError)

### ISSUE THREAD

**Issue by anthonyrisinger** [wickman/pesos#21]
while trying to adapt the Mesos official python example to use pesos instead, I triggered this:

```
Traceback (most recent call last):
  File "example_framework.py", line 159, in <module>
    status = 0 if driver.run() == mesos_pb2.DRIVER_STOPPED else 1
  File "/path/to/lib/python2.7/site-packages/pesos/scheduler.py", line 371, in _wrapper
    return method(self, *args, **kw)
  File "/path/to/lib/python2.7/site-packages/pesos/scheduler.py", line 437, in run
    self.status = self.start()
  File "/path/to/lib/python2.7/site-packages/pesos/scheduler.py", line 371, in _wrapper
    return method(self, *args, **kw)
  File "/path/to/lib/python2.7/site-packages/pesos/scheduler.py", line 380, in start
    self.detector = MasterDetector.from_uri(self.master_uri)
  File "/path/to/lib/python2.7/site-packages/pesos/detector.py", line 58, in from_uri
    raise cls.CannotDetector('No compatible master detectors found for %r' % uri)
AttributeError: type object 'MasterDetector' has no attribute 'CannotDetector'
```

regardless of how it happened, nothing named `CannotDetector` exists in the project, and was probably a typo for `CannotDetect`.

**Comment by anthonyrisinger** [comment]
the issue arose due to passing `172.17.0.207:5050` as `master_uri` instead of `master@172.17.0.207:5050`, but that did not get me there due to other problems :(

**Comment by tarnfeld** [comment]
Have you tried running from my PR https://github.com/wickman/pesos/pull/19?

**Comment by anthonyrisinger** [comment]
no i have not, but your changes look 100% legit to me, and would take care of this specific issue.

once that PR lands i will close this ticket (if not already closed).
