### ISSUE TITLE
non-obvious constraints on the protobuf source

### ISSUE THREAD

**Issue by anthonyrisinger** [wickman/pesos#22]
Some examples/bugreports elsewhere suggest the `mesos.interface.mesos_pb2` module and `pesos.vendor.mesos.mesos_pb2` are the same (and potentially the _exact_ same module if the `mesos.interface` package exists).

However, if you try to start a driver using `mesos.interface.mesos_pb2.FrameworkInfo`:

``` python
framework = mesos_pb2.FrameworkInfo(
    user='root',
    name='Test Framework (Python)',
    principal='test-framework-python',
    )

driver = PesosSchedulerDriver(
    scheduler=TestScheduler(),
    framework=framework,
    master_uri=sys.argv[1],
    )
```

You end up with:

```
ERROR:tornado.application:Exception in callback <functools.partial object at 0x7fe4d101d680>
Traceback (most recent call last):
  File "/path/to/lib/python2.7/site-packages/tornado/ioloop.py", line 568, in _run_callback
    ret = callback()
  File "/path/to/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/path/to/lib/python2.7/site-packages/pesos/scheduler.py", line 64, in detect
    self.detector.detect(previous=self.master).add_done_callback(self.detected)
  File "/path/to/lib/python2.7/site-packages/concurrent/futures/_base.py", line 375, in add_done_callback
    fn(self)
  File "/path/to/lib/python2.7/site-packages/pesos/scheduler.py", line 72, in _wrapper
    return method(self, from_pid, *args, **kwargs)
  File "/path/to/lib/python2.7/site-packages/pesos/scheduler.py", line 113, in detected
    self._do_registration()
  File "/path/to/lib/python2.7/site-packages/pesos/scheduler.py", line 126, in _do_registration
    message = internal.RegisterFrameworkMessage(framework=self.framework)
  File "build/bdist.linux-x86_64/egg/google/protobuf/internal/python_message.py", line 355, in init
    _ReraiseTypeErrorWithFieldName(message_descriptor.name, field_name)
  File "build/bdist.linux-x86_64/egg/google/protobuf/internal/python_message.py", line 353, in init
    copy.MergeFrom(field_value)
  File "build/bdist.linux-x86_64/egg/google/protobuf/internal/python_message.py", line 989, in MergeFrom
    "expected %s got %s." % (cls.__name__, type(msg).__name__))
TypeError: Parameter to MergeFrom() must be instance of same class: expected FrameworkInfo got FrameworkInfo. for field RegisterFrameworkMessage.framework
```

Changing the import to use the `pesos.vendor` version fixes this, but is unexpected (`pesos.scheduler` and `pesos.executor` both use `mesos.interface`, albeit not the protobufs).

**Comment by tarnfeld** [comment]
[This conversation](https://github.com/wickman/pesos/commit/0f3b3cec5fee48c91381080e2bea5493fbd19eae#commitcomment-10448013) might be relevant. You need to use the protos you can import via `pesos.vendor` instead because of this protobuf issue.

**Comment by anthonyrisinger** [comment]
ah, yep. fair enough. thanks for the pointer @tarnfeld !

closing as pretty much WONTFIX :)
